---
template_dir: 'template'
public_dir: 'public'
pages_dir: 'pages'
output_dir: 'docs' # use 'docs' to integrate with GitHub Pages
default_template: 'page'
posts_dir: 'posts'
post_index_template: 'posts-index.html'
base_url: '/pysite' # CHANGE to the subdirectory of your site
---